"""Add Seed Data

Revision ID: 91f1c66cdd82
Revises: 69aea3751050
Create Date: 2023-10-16 06:03:01.155539

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91f1c66cdd82'
down_revision: Union[str, None] = '69aea3751050'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    insert_user_sql = """
    INSERT INTO "user" ("id", "username", "email", "password") VALUES
    (1,	'admin2',	'admin2@gmail.com',	'$2b$12$AdMChzE9ch5Ylqhb2.WsQ.p7cNg/7qCT1BbEKtjFqF2aj/lAWyNxy');
    """
    insert_author_sql = """
    INSERT INTO "author" ("id", "name") VALUES
    (1,	'Conan Doyle'),(2,	'George R. R. Martin');
    """
    insert_book_sql = """
    INSERT INTO "book" ("id", "title", "num_pages", "author_id") VALUES
    (1,	'The Study in Scarlet',	0,	1),
    (2,	'The Adventures of Sherlock Holmes',	20,	1),
    (3,	'Game of Thrones',	0,	2);
    """
    op.execute(insert_user_sql)
    op.execute(insert_author_sql)
    op.execute(insert_book_sql)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    delete_user_sql = """
    DELETE FROM "user" WHERE "id" = 1;
    """
    delete_author_sql = """
    DELETE FROM "author" WHERE "id" in (1, 2);
    """
    delete_book_sql = """
    DELETE FROM "book" WHERE "id" in (1, 2, 3);
    """
    op.execute(delete_user_sql)
    op.execute(delete_author_sql)
    op.execute(delete_book_sql)
    # ### end Alembic commands ###
